## To modify by developer(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'trinamic'

package-url = 'https://github.com/ccabello99/pymodaq_plugins_trinamic' #to modify
description = 'PyMoDAQ module for communication and readout from Trinamic stepper motor control units'

author = 'Christian Cabello'
author-email = 'christian.cabello@ip-paris.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq', 'pytrinamic']

[features]  # defines the plugin features contained into this plugin
instruments = true  # true if plugin contains instrument classes (else false, notice the lowercase for toml files)
extensions = false  # true if plugins contains dashboard extensions
models = false  # true if plugins contains pid models or other models (optimisation...)
h5exporters = false  # true if plugin contains custom h5 file exporters
scanners = false  # true if plugin contains custom scan layout (daq_scan extensions)

